<?php

namespace FabricationBundle\Repository;

/**
 * ProductsFabricationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsFabricationRepository extends \Doctrine\ORM\EntityRepository
{
}
