<?php

namespace FabricationBundle\Repository;

/**
 * StockFabricationMovementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockFabricationMovementRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAll(){
        $table = $this->getEntityManager()->getClassMetadata("FabricationBundle:StockFabricationMovement")->getTableName();
        $join1 = $this->getEntityManager()->getClassMetadata("FabricationBundle:ProductsFabrication")->getTableName();
        $join2 = $this->getEntityManager()->getClassMetadata("FabricationBundle:Fournisseur")->getTableName();
        $join3 = $this->getEntityManager()->getClassMetadata("AuthBundle:User")->getTableName();
        $sql  = "SELECT a.*, IFNULL(b.name, '--') product, IFNULL(c.name, '--') as fournisseur, IFNULL(CONCAT(d.firstname,' ',d.lastname), '--') as user FROM $table a";
        $sql .= " LEFT JOIN $join1 b ON b.id = a.id_product";
        $sql .= " LEFT JOIN $join2 c ON c.id = a.id_fournisseur ";
        $sql .= " LEFT JOIN $join3 d ON d.id_user = a.id_user ";
        $stmt = $this->getEntityManager()
            ->getConnection()
            ->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }
}
