sales:
    resource: "@SalesBundle/Controller/"
    type:     annotation
    prefix:   /

fabrication:
    resource: "@FabricationBundle/Controller/"
    type:     annotation
    prefix:   /

auth:
    resource: "@AuthBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@AuthBundle/Resources/config/routing/all.xml"

