<?php

namespace SalesBundle\Repository;

/**
 * CarrierMethodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarrierMethodRepository extends \Doctrine\ORM\EntityRepository
{
}
