<?php

namespace SalesBundle\Repository;

/**
 * SalesProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesProductRepository extends \Doctrine\ORM\EntityRepository
{
}
