<?php

namespace AuthBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getUsers($limit, $page, $desc, $orderBy, $q)
    {
        $query = $this->getEntityManager()
            ->createQueryBuilder()
            ->select("u.id as id, u.username as username, u.email as email, u.enabled as status,u.lastLogin as lastLogin, u.roles as roles, u.firstname as firstname, u.lastname as lastname, u.menu as menus")
            ->from('AuthBundle:User', 'u')
            ->where("u.id > 0");

        $query1 = $this->getEntityManager()
            ->createQueryBuilder()
            ->select("COUNT(u.id) as count")
            ->from('AuthBundle:User', 'u')
            ->where("u.id > 0");


        if (!empty($q)) {
            foreach ($q as $key => $val) {
                $query->andwhere("u.$key LIKE '%$val%'");
                $query1->andwhere("u.$key LIKE '%$val%'");
            }
        }

        if ($orderBy != '') :
            $query->orderBy("u.$orderBy", ($desc) ? 'DESC' : 'ASC');
        endif;

        $count = $query1->getQuery()->getOneOrNullResult();

        if($limit == -1){
            $results = $query->getQuery()->getArrayResult();
        }else{
            $paginator = new Paginator($query,false);
            $paginator->getQuery()
                ->setFirstResult($limit * ($page - 1))
                ->setMaxResults($limit);

            $results = $paginator->getIterator()->getArrayCopy();
        }
        foreach($results as &$result){
			$records["data"][] = array(
			  '<input type="checkbox" name="id[]" value="'.$result['id'].'">',
			  $result['id'],
			  $result['username'],
			  $result['email'],
			  $result['lastLogin']->format('Y-m-d H:i:s'),
			  implode($result['roles'],'<br>'),
			  $result['firstname'].' '.$result['lastname'],
			  $result['status'],
			  '<a href="#" class="btn btn-xs default btn-editable"><i class="fa fa-search"></i> View</a>',
			);

        }
		$records["recordsTotal"] = $count['count'];
		$records["recordsFiltered"] = $count['count'];
		
        return $records;
    }
}
