<?php

namespace AuthBundle\Repository;

/**
 * UserMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
