<?php

namespace AuthBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /*
     * Get Users
     * @param boolean $active
     * @param array $id_sites
     * @param string $sort
     * @param string $direction
     * @param string $searchQuery
     * @return array sites
     */
    public function getUsers ($active = true, $id_sites = array(), $sort = '', $direction = '', $searchQuery = '') {
        $query = $this->_em->createQueryBuilder('u')
            ->select('u')
                //->addSelect('(SELECT COUNT(so1.id_customer) FROM DataSiteBundle:SiteOrder so1 WHERE so1.id_customer = sc.id_customer_site AND so1.id_site = sc.id_site) as orders')//, HIDDEN
                //->addSelect('(SELECT IF(SUM(so2.total_paid_tax_incl / so2.conversion_rate) IS NULL, 0, SUM(so2.total_paid_tax_incl / so2.conversion_rate)) FROM DataSiteBundle:SiteOrder so2 WHERE so2.id_customer = sc.id_customer_site AND so2.id_site = sc.id_site) as sales')//, HIDDEN
            ->from($this->_entityName, 'u');
        
        if($active) :
            $query->andWhere('u.active = :active')->setParameter('active', (int)$active);
        endif;
        
        if(count($id_sites)) :
            //$query->andWhere('u.id IN (:id_site)')->setParameter('id_site', $id_sites);
        endif;  
        
        if($searchQuery) :
            $query->andWhere('u.id LIKE :searchQuery OR u.username LIKE :searchQuery OR u.lastname LIKE :searchQuery OR u.firstname LIKE :searchQuery OR u.email LIKE :searchQuery')->setParameter('searchQuery', '%'.$searchQuery.'%');
        endif;
        
        if($sort && $direction) :
            $query->orderBy($sort, $direction);
        else :
            $query->orderBy('u.username', 'ASC');
        endif;
        
        
        $users = $query->getQuery()->getResult();
            
        //echo '<pre>';
        //print_r($query->getSql());
        //die('end');
        //$sites = $query->getResult();

        return $users;
    }
}
